### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by mohammad2k** [Sebastian09-09/InstaDM#1]
TypeError: Cannot read properties of undefined (reading 'close')
    at loginInstagramFunc (C:\Users\moham\Desktop\InstaDM-main\app.js:381:23)
    
    Something went wrong while Logging In 💀

hi there please check this. I can't log in

**Comment by Sebastian09-09** [comment]
Hey!
Here are some steps you can try to resolve the issue :-
1) Make sure your password is correct
2) Make sure 2-Factor Authentication is turned off
3) Login with the same account in your browser , to check if everything is working fine
4) Try to Login Again
